### ISSUE TITLE
possible conflict with hoodselector

### ISSUE THREAD

**Issue by lrnzo** [tecff/gluon-packages#4]
without having done much research here, i think there might be a conflict between the packages gluon-hoodselector (see [here](/gluon/pull/1393https://github.com/freifunk-gluon)) and tecff-autoupdater-wifi-fallback. In the current Freifunk Nordwest Firmware as of 20180709 these two packages are build in  and i am observe several routers with a weird /etc/config/wirless, e.g.

```
config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11g'
	option path 'platform/qca956x_wmac'
	option htmode 'HT20'
	option channel '6'
	option country 'DE'
	list supported_rates '6000'
	list supported_rates '9000'
	list supported_rates '12000'
	list supported_rates '18000'
	list supported_rates '24000'
	list supported_rates '36000'
	list supported_rates '48000'
	list supported_rates '54000'
	list basic_rate '6000'
	list basic_rate '9000'
	list basic_rate '18000'
	list basic_rate '36000'
	list basic_rate '54000'
	option disabled '0'

config wifi-iface 'fallback'
	option ifname 'fallback'
	option network 'fallback'
	option encryption 'none'
	option device 'radio0'
	option bssid 'E6:6C:EF:61:05:60'
	option ssid 'nordwest.freifunk.net'
	option mode 'sta'
	option macaddr 'f2:8e:90:95:19:bb'
	option disabled '0'

config wifi-iface 'mesh_radio0'
	option mesh_id 'ffnw-mesh_02:00:0a:12:e0:00'
```

The `config wifi-iface 'fallback'` clearly comes from a run of the `local function switch_to_fallback_mode`. The following and inclompete `config wifi-iface 'mesh_radio0'` comes from a run of the hoodselector, which sets, saves and commits the `option mesh_id`. My assumption is that this sometimes just happens within the timeframe of a few seconds before the `uci:revert('wireless')`. From there on the router will never get back to its normal mode.

**Comment by rotanid** [comment]
thanks for your report. as we don't use domains or hoods yet, i can't really help with this issue.
i'm happy to include a good fix if someone provides it.

**Comment by lrnzo** [comment]
one possible fix could be to disable the hoodselector via uci while the fallback_mode is acitve. Maybe i can provide this fix in the evening.

**Comment by rotanid** [comment]
@lrnzo do you still want to provide a fix or can i close this issue? maybe you have already created a fix in your local copy of this script?

**Comment by lrnzo** [comment]
locally we solved the problem by not using the tecff-autoupdater-wifi-fallback package in our firmware. currently i am not planning on a fix. sorry for maybe letting people wait.

**Comment by rotanid** [comment]
no problem :)
